### ISSUE TITLE
CSA stops too early

### ISSUE THREAD

**Issue by brechtvdv** [linkedconnections/csa.js#14]
Now the algorithm stops when it scanned a connection with arrival stop equal to the query destination.
I believe this is not 100% proof that it's the Earliest Arrival Time.

As stated in the 'Intriguingly Simple and Fast Transit Routing' paper:

`the algorithm may stop as soon as it scans a connection
whose departure time exceeds the target stop’s earliest arrival time.`

So I believe we need to scan a bit futher until this condition is met.

**Comment by pietercolpaert** [comment]
indeed! You're right
