### ISSUE TITLE
End of stream event not fired

### ISSUE THREAD

**Issue by rodklerc** [linkedconnections/csa.js#17]
Consider the following example code:

```
    var query = {departureStop: ..., departureTime: ...};
    var fetcher = new Fetcher(...);
    var planner = new BasicCSA(query);
    fetcher.buildConnectionsStream(query, function (connectionsStream) {
      connectionsStream.pipe(planner).on('end', function () { console.log('stream ended'); });
    }
```

The line "console.log('stream ended');" is never executed, indicating that the stream generated by the planner has not ended.

Commenting out lines 116-121 in BasicCSA.js temporarily fixes this problem.

**Comment by pietercolpaert** [comment]
Lines 116-121: https://github.com/linkedconnections/csa.js/blob/master/lib/BasicCSA.js#L116-L121
