### ISSUE TITLE
Feature parent station

### ISSUE THREAD

**Issue by brechtvdv** [linkedconnections/csa.js#4]
Some datasets only work with stops that are the combination of the parent_station and platform_code.

A connection should have `lc:arrivalParentStation` and `lc:departureParentStation` properties when available.

**Comment by pietercolpaert** [comment]
- Concerning properties: use `gtfs:parentStation`. No need for the properties you suggest
- I believe this is a duplicate of https://github.com/linkedconnections/csa.js/issues/1

**Comment by pietercolpaert** [comment]
I'll close this one for now as duplicate of #1
